
node {
  
    environment {
    imageName = "myapp"
    registryCredentials = "nexusid1"
    registry = "35.172.201.214:8083"
    dockerImage = ''
  }
  
  def image
  def mvnHome = tool 'maven3'

  
    // stage ('checkout') {
    //    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '9ffd4ee4-3647-4a7d-a357-5e8746463282', url: 'https://bitbucket.org/ananthkannan/myawesomeangularapprepo/']]])       
    //    }
    
    
    stage ('Build') {
            sh 'mvn -f MyAwesomeApp/pom.xml clean install'            
        }
        
    stage ('archive') {
            archiveArtifacts '**/*.jar'
        }
        
    stage('Build Docker image') {
      steps {
        script {
          dockerImage = docker.build(imageName)
        }
      }
    }
    stage('Upload Docker image into Repo') {
      steps {
        script {
          docker.withRegistry('http://' + registry, registryCredentials) {
            dockerImage.push("latest")
          }
        }
      }
    }

}
